type Base = { src: string, alt: string, width: number, height: number, creator?: string, date: string, people: string[], type: string }
export type GalleryItem = 
    | (Base & { kind: 'image' })
    | (Base & { kind: 'video', poster: string })

export const GALLERY: GalleryItem[] = [
  {
    kind: 'image',
    src: '/slander-gallery/MarkAndrewsMissing.jpg',
    alt: '',
    width: 585, height: 524,
    creator: 'logan',
    date: '2024-09-06',
    people: ['matt'],
    type: 'meme',
  },
  {
    kind: 'image',
    src: '/slander-gallery/AutopickNickSixText.jpg',
    alt: '',
    width: 1179, height: 699,
    date: '2024-09-09',
    people: ['nick'],
    type: 'text',
  },
  {
    kind: 'image',
    src: '/slander-gallery/EthanCooked.jpg',
    alt: '',
    width: 404, height: 404,
    creator: 'logan',
    date: '2024-09-10',
    people: ['ethan'],
    type: 'meme',
  },
  {
    kind: 'image',
    src: '/slander-gallery/WhieldonIced.jpg',
    alt: '',
    width: 375, height: 375,
    creator: 'logan',
    date: '2024-09-10',
    people: ['whieldon'],
    type: 'meme',
  },
  {
    kind: 'image',
    src: '/slander-gallery/RobertNickSixed.jpg',
    alt: '',
    width: 500, height: 500,
    creator: 'logan',
    date: '2024-09-10',
    people: ['nick', 'robert'],
    type: 'graphic',
  },
  {
    kind: 'image',
    src: '/slander-gallery/NickSixESPN.jpg',
    alt: '',
    width: 585, height: 713,
    creator: 'logan',
    date: '2024-09-10',
    people: ['nick', 'robert'],
    type: 'espn',
  },
  {
    kind: 'image',
    src: '/slander-gallery/NickEthanOnePoint.jpg',
    alt: '',
    width: 1179, height: 2556,
    creator: 'andy',
    date: '2024-09-16',
    people: ['nick', 'ethan'],
    type: 'espn',
  },
  {
    kind: 'image',
    src: '/slander-gallery/DillonAsleepLogan.jpg',
    alt: '',
    width: 1000, height: 1000,
    creator: 'logan',
    date: '2024-10-04',
    people: ['dillon', 'logan'],
    type: 'meme',
  },
  {
    kind: 'image',
    src: '/slander-gallery/WhieldonBroken.jpg',
    alt: '',
    width: 965, height: 1000,
    creator: 'logan',
    date: '2024-10-04',
    people: ['whieldon'],
    type: 'meme',
  },
  {
    kind: 'image',
    src: '/slander-gallery/DillonCMCNews.jpg',
    alt: '',
    width: 750, height: 1000,
    creator: 'logan',
    date: '2024-10-04',
    people: ['dillon'],
    type: 'meme',
  },
  {
    kind: 'image',
    src: '/slander-gallery/DidNickWinGuys.jpg',
    alt: '',
    width: 608, height: 632,
    date: '2024-10-14',
    people: ['nick', 'robert'],
    type: 'text',
  },
  {
    kind: 'image',
    src: '/slander-gallery/RobertEthanRecap.jpg',
    alt: '',
    width: 1179, height: 1191,
    creator: 'robert',
    date: '2024-10-15',
    people: ['ethan', 'robert'],
    type: 'espn',
  },
  {
    kind: 'image',
    src: '/slander-gallery/WhieldonPyrrhicVictory.jpg',
    alt: '',
    width: 1600, height: 670,
    creator: 'logan',
    date: '2024-10-21',
    people: ['whieldon', 'robert'],
    type: 'meme',
  },
  {
    kind: 'image',
    src: '/slander-gallery/LeagueElite.jpg',
    alt: '',
    width: 680, height: 522,
    creator: 'logan',
    date: '2024-10-22',
    people: ['logan', 'matt', 'robert', 'andy', 'max', 'whieldon', 'dillon', 'ethan', 'james', 'nick'],
    type: 'meme',
  },
  {
    kind: 'image',
    src: '/slander-gallery/LoganElitePull.jpg',
    alt: '',
    width: 948, height: 1257,
    creator: 'andy',
    date: '2024-10-22',
    people: ['logan'],
    type: 'meme',
  },
  {
    kind: 'image',
    src: '/slander-gallery/MattBaller.jpg',
    alt: '',
    width: 806, height: 1382,
    creator: 'andy',
    date: '2024-10-22',
    people: ['matt'],
    type: 'meme',
  },
  {
    kind: 'image',
    src: '/slander-gallery/AndyPotentialFraud.jpg',
    alt: '',
    width: 1200, height: 1056,
    creator: 'robert',
    date: '2024-11-10',
    people: ['andy'],
    type: 'meme',
  },
  {
    kind: 'image',
    src: '/slander-gallery/EthanJamarrSisyphus.jpg',
    alt: '',
    width: 947, height: 1168,
    creator: 'robert',
    date: '2024-11-10',
    people: ['ethan'],
    type: 'meme',
  },
  {
    kind: 'image',
    src: '/slander-gallery/ProjectedPlayoffs.jpg',
    alt: '',
    width: 1600, height: 900,
    creator: 'logan',
    date: '2024-11-11',
    people: ['logan', 'matt', 'robert', 'andy', 'max', 'whieldon', 'dillon', 'ethan', 'james', 'nick'],
    type: 'graphic',
  },
  {
    kind: 'image',
    src: '/slander-gallery/DillonEliminated.jpg',
    alt: '',
    width: 1080, height: 1350,
    creator: 'logan',
    date: '2024-11-12',
    people: ['dillon'],
    type: 'graphic',
  },
  {
    kind: 'image',
    src: '/slander-gallery/JamesEliminated.jpg',
    alt: '',
    width: 1080, height: 1350,
    creator: 'logan',
    date: '2024-11-12',
    people: ['james'],
    type: 'graphic',
  },
  {
    kind: 'image',
    src: '/slander-gallery/NickEliminated.jpg',
    alt: '',
    width: 1000, height: 453,
    creator: 'logan',
    date: '2024-11-19',
    people: ['nick'],
    type: 'graphic',
  },
  {
    kind: 'image',
    src: '/slander-gallery/DillonAss.jpg',
    alt: '',
    width: 1000, height: 1000,
    creator: 'logan',
    date: '2024-11-24',
    people: ['dillon'],
    type: 'graphic',
  },
  {
    kind: 'image',
    src: '/slander-gallery/EthanWhieldonParallels.jpg',
    alt: '',
    width: 750, height: 606,
    creator: 'logan',
    date: '2024-11-24',
    people: ['ethan', 'whieldon'],
    type: 'meme',
  },
  {
    kind: 'image',
    src: '/slander-gallery/LoganDomination.jpg',
    alt: '',
    width: 1179, height: 1949,
    creator: 'andy',
    date: '2024-11-24',
    people: ['logan', 'ethan', 'andy'],
    type: 'espn',
  },
  {
    kind: 'image',
    src: '/slander-gallery/LoganRomantical.jpg',
    alt: '',
    width: 1179, height: 1145,
    date: '2024-11-24',
    people: ['logan', 'ethan', 'andy'],
    type: 'text',
  },
  {
    kind: 'image',
    src: '/slander-gallery/WhieldonEliminated.jpg',
    alt: '',
    width: 2160, height: 2374,
    creator: 'logan',
    date: '2024-11-26',
    people: ['whieldon'],
    type: 'graphic',
  },
  {
    kind: 'image',
    src: '/slander-gallery/LoganClinched.jpg',
    alt: '',
    width: 1096, height: 1354,
    creator: 'andy',
    date: '2024-12-02',
    people: ['logan'],
    type: 'graphic',
  },
  // TODO: NICK SIX VIDEO
  // TODO: DILLON W 3-10 VIDEO
  {
    kind: 'image',
    src: '/slander-gallery/PlayoffTierlist.jpg',
    alt: '',
    width: 1140, height: 723,
    creator: 'andy',
    date: '2024-12-07',
    people: ['logan', 'matt', 'robert', 'andy', 'max', 'whieldon', 'dillon', 'ethan', 'james', 'nick'],
    type: 'graphic',
  },
  {
    kind: 'image',
    src: '/slander-gallery/RobertClinched.jpg',
    alt: '',
    width: 1024, height: 512,
    creator: 'logan',
    date: '2024-12-08',
    people: ['robert'],
    type: 'graphic',
  },
  {
    kind: 'image',
    src: '/slander-gallery/CWECoffeeChat.png',
    alt: '',
    width: 948, height: 1086,
    date: '2024-12-08',
    people: ['max', 'robert'],
    type: 'text',
  },
  {
    kind: 'image',
    src: '/slander-gallery/NickOwnsAndy.jpg',
    alt: '',
    width: 1170, height: 1435,
    creator: 'logan',
    date: '2024-12-10',
    people: ['nick', 'andy'],
    type: 'text',
  },
  {
    kind: 'image',
    src: '/slander-gallery/EthanClinched.jpg',
    alt: '',
    width: 3840, height: 2160,
    creator: 'logan',
    date: '2024-12-10',
    people: ['ethan'],
    type: 'graphic',
  },
  {
    kind: 'image',
    src: '/slander-gallery/MattClinched.jpg',
    alt: '',
    width: 3003, height: 1998,
    creator: 'logan',
    date: '2024-12-13',
    people: ['matt'],
    type: 'graphic',
  },
  {
    kind: 'image',
    src: '/slander-gallery/AndyEliminated.jpg',
    alt: '',
    width: 2160, height: 2411,
    creator: 'logan',
    date: '2024-12-13',
    people: ['andy'],
    type: 'graphic',
  },
  {
    kind: 'image',
    src: '/slander-gallery/MaxEliminated.jpg',
    alt: '',
    width: 1179, height: 881,
    creator: 'logan',
    date: '2024-12-13',
    people: ['max'],
    type: 'graphic',
  }
]