type Base = { alt: string, width: number, height: number, creator?: string, date: string, people: string[], type: string }
export type GalleryItem = 
    | (Base & { kind: 'image', src: string })
    | (Base & { kind: 'video', src: string, poster: string })
    | (Base & { kind: 'youtube', videoId: string, poster?: string })

export const keyOf = (i: GalleryItem) => i.kind === 'youtube' ? `yt:${i.videoId}` : i.src
export const posterOf = (i: GalleryItem) =>
  i.kind === 'image' ? i.src
  : i.poster ?? (i.kind === 'video' ? i.src.replace(/\.[^.]+$/, '.jpg') : `https://i.ytimg.com/vi/${i.videoId}/hqdefault.jpg`)

export const GALLERY: GalleryItem[] = [
  {
    kind: 'image',
    src: '/slander-gallery/MarkAndrewsMissing.jpg',
    alt: '',
    width: 585, height: 524,
    creator: 'logan',
    date: '2024-09-06',
    people: ['matt'],
    type: 'meme',
  },
  {
    kind: 'image',
    src: '/slander-gallery/AutopickNickSixText.jpg',
    alt: '',
    width: 1179, height: 699,
    date: '2024-09-09',
    people: ['nick'],
    type: 'text',
  },
  {
    kind: 'image',
    src: '/slander-gallery/EthanCooked.jpg',
    alt: '',
    width: 404, height: 404,
    creator: 'logan',
    date: '2024-09-10',
    people: ['ethan'],
    type: 'meme',
  },
  {
    kind: 'image',
    src: '/slander-gallery/WhieldonIced.jpg',
    alt: '',
    width: 375, height: 375,
    creator: 'logan',
    date: '2024-09-10',
    people: ['whieldon'],
    type: 'meme',
  },
  {
    kind: 'image',
    src: '/slander-gallery/RobertNickSixed.jpg',
    alt: '',
    width: 500, height: 500,
    creator: 'logan',
    date: '2024-09-10',
    people: ['nick', 'robert'],
    type: 'graphic',
  },
  {
    kind: 'image',
    src: '/slander-gallery/NickSixESPN.jpg',
    alt: '',
    width: 585, height: 713,
    creator: 'logan',
    date: '2024-09-10',
    people: ['nick', 'robert'],
    type: 'espn',
  },
  {
    kind: 'image',
    src: '/slander-gallery/NickEthanOnePoint.jpg',
    alt: '',
    width: 1179, height: 2556,
    creator: 'andy',
    date: '2024-09-16',
    people: ['nick', 'ethan'],
    type: 'espn',
  },
  {
    kind: 'image',
    src: '/slander-gallery/DillonAsleepLogan.jpg',
    alt: '',
    width: 1000, height: 1000,
    creator: 'logan',
    date: '2024-10-04',
    people: ['dillon', 'logan'],
    type: 'meme',
  },
  {
    kind: 'image',
    src: '/slander-gallery/WhieldonBroken.jpg',
    alt: '',
    width: 965, height: 1000,
    creator: 'logan',
    date: '2024-10-04',
    people: ['whieldon'],
    type: 'meme',
  },
  {
    kind: 'image',
    src: '/slander-gallery/DillonCMCNews.jpg',
    alt: '',
    width: 750, height: 1000,
    creator: 'logan',
    date: '2024-10-04',
    people: ['dillon'],
    type: 'meme',
  },
  {
    kind: 'image',
    src: '/slander-gallery/DidNickWinGuys.jpg',
    alt: '',
    width: 608, height: 632,
    date: '2024-10-14',
    people: ['nick', 'robert'],
    type: 'text',
  },
  {
    kind: 'image',
    src: '/slander-gallery/RobertEthanRecap.jpg',
    alt: '',
    width: 1179, height: 1191,
    creator: 'robert',
    date: '2024-10-15',
    people: ['ethan', 'robert'],
    type: 'espn',
  },
  {
    kind: 'image',
    src: '/slander-gallery/WhieldonPyrrhicVictory.jpg',
    alt: '',
    width: 1600, height: 670,
    creator: 'logan',
    date: '2024-10-21',
    people: ['whieldon', 'robert'],
    type: 'meme',
  },
  {
    kind: 'image',
    src: '/slander-gallery/LeagueElite.jpg',
    alt: '',
    width: 680, height: 522,
    creator: 'logan',
    date: '2024-10-22',
    people: ['logan', 'matt', 'robert', 'andy', 'max', 'whieldon', 'dillon', 'ethan', 'james', 'nick'],
    type: 'meme',
  },
  {
    kind: 'image',
    src: '/slander-gallery/LoganElitePull.jpg',
    alt: '',
    width: 948, height: 1257,
    creator: 'andy',
    date: '2024-10-22',
    people: ['logan'],
    type: 'meme',
  },
  {
    kind: 'image',
    src: '/slander-gallery/MattBaller.jpg',
    alt: '',
    width: 806, height: 1382,
    creator: 'andy',
    date: '2024-10-22',
    people: ['matt'],
    type: 'meme',
  },
  {
    kind: 'image',
    src: '/slander-gallery/AndyPotentialFraud.jpg',
    alt: '',
    width: 1200, height: 1056,
    creator: 'robert',
    date: '2024-11-10',
    people: ['andy'],
    type: 'meme',
  },
  {
    kind: 'image',
    src: '/slander-gallery/EthanJamarrSisyphus.jpg',
    alt: '',
    width: 947, height: 1168,
    creator: 'robert',
    date: '2024-11-10',
    people: ['ethan'],
    type: 'meme',
  },
  {
    kind: 'image',
    src: '/slander-gallery/ProjectedPlayoffs.jpg',
    alt: '',
    width: 1600, height: 900,
    creator: 'logan',
    date: '2024-11-11',
    people: ['logan', 'matt', 'robert', 'andy', 'max', 'whieldon', 'dillon', 'ethan', 'james', 'nick'],
    type: 'graphic',
  },
  {
    kind: 'image',
    src: '/slander-gallery/DillonEliminated.jpg',
    alt: '',
    width: 1080, height: 1350,
    creator: 'logan',
    date: '2024-11-12',
    people: ['dillon'],
    type: 'graphic',
  },
  {
    kind: 'image',
    src: '/slander-gallery/JamesEliminated.jpg',
    alt: '',
    width: 1080, height: 1350,
    creator: 'logan',
    date: '2024-11-12',
    people: ['james'],
    type: 'graphic',
  },
  {
    kind: 'image',
    src: '/slander-gallery/NickEliminated.jpg',
    alt: '',
    width: 1000, height: 453,
    creator: 'logan',
    date: '2024-11-19',
    people: ['nick'],
    type: 'graphic',
  },
  {
    kind: 'image',
    src: '/slander-gallery/DillonAss.jpg',
    alt: '',
    width: 1000, height: 1000,
    creator: 'logan',
    date: '2024-11-24',
    people: ['dillon'],
    type: 'graphic',
  },
  {
    kind: 'image',
    src: '/slander-gallery/EthanWhieldonParallels.jpg',
    alt: '',
    width: 750, height: 606,
    creator: 'logan',
    date: '2024-11-24',
    people: ['ethan', 'whieldon'],
    type: 'meme',
  },
  {
    kind: 'image',
    src: '/slander-gallery/LoganDomination.jpg',
    alt: '',
    width: 1179, height: 1949,
    creator: 'andy',
    date: '2024-11-24',
    people: ['logan', 'ethan', 'andy'],
    type: 'espn',
  },
  {
    kind: 'image',
    src: '/slander-gallery/LoganRomantical.jpg',
    alt: '',
    width: 1179, height: 1145,
    date: '2024-11-24',
    people: ['logan', 'ethan', 'andy'],
    type: 'text',
  },
  {
    kind: 'image',
    src: '/slander-gallery/WhieldonEliminated.jpg',
    alt: '',
    width: 2160, height: 2374,
    creator: 'logan',
    date: '2024-11-26',
    people: ['whieldon'],
    type: 'graphic',
  },
  {
    kind: 'image',
    src: '/slander-gallery/LoganClinched.jpg',
    alt: '',
    width: 1096, height: 1354,
    creator: 'andy',
    date: '2024-12-02',
    people: ['logan'],
    type: 'graphic',
  },
  {
    kind: 'video',
    src: '/slander-gallery/NickSix.mov',
    alt: '',
    width: 640, height: 360,
    creator: 'logan',
    date: '2024-12-02',
    people: ['nick', 'robert'],
    type: 'video',
    poster: '/slander-gallery/NickSix.jpg',
  },
  {
    kind: 'video',
    src: '/slander-gallery/DillonJumpscare.mov',
    alt: '',
    width: 640, height: 310,
    creator: 'robert',
    date: '2024-12-05',
    people: ['dillon'],
    type: 'video',
    poster: '/slander-gallery/DillonJumpscare.jpg',
  },
  {
    kind: 'image',
    src: '/slander-gallery/PlayoffTierlist.jpg',
    alt: '',
    width: 1140, height: 723,
    creator: 'andy',
    date: '2024-12-07',
    people: ['logan', 'matt', 'robert', 'andy', 'max', 'whieldon', 'dillon', 'ethan', 'james', 'nick'],
    type: 'graphic',
  },
  {
    kind: 'image',
    src: '/slander-gallery/RobertClinched.jpg',
    alt: '',
    width: 1024, height: 512,
    creator: 'logan',
    date: '2024-12-08',
    people: ['robert'],
    type: 'graphic',
  },
  {
    kind: 'image',
    src: '/slander-gallery/CWECoffeeChat.png',
    alt: '',
    width: 948, height: 1086,
    date: '2024-12-08',
    people: ['max', 'robert'],
    type: 'text',
  },
  {
    kind: 'image',
    src: '/slander-gallery/NickOwnsAndy.jpg',
    alt: '',
    width: 1170, height: 1435,
    creator: 'logan',
    date: '2024-12-10',
    people: ['nick', 'andy'],
    type: 'text',
  },
  {
    kind: 'image',
    src: '/slander-gallery/EthanClinched.jpg',
    alt: '',
    width: 3840, height: 2160,
    creator: 'logan',
    date: '2024-12-10',
    people: ['ethan'],
    type: 'graphic',
  },
  {
    kind: 'image',
    src: '/slander-gallery/MattClinched.jpg',
    alt: '',
    width: 3003, height: 1998,
    creator: 'logan',
    date: '2024-12-13',
    people: ['matt'],
    type: 'graphic',
  },
  {
    kind: 'image',
    src: '/slander-gallery/AndyEliminated.jpg',
    alt: '',
    width: 2160, height: 2411,
    creator: 'logan',
    date: '2024-12-13',
    people: ['andy'],
    type: 'graphic',
  },
  {
    kind: 'image',
    src: '/slander-gallery/MaxEliminated.jpg',
    alt: '',
    width: 1179, height: 881,
    creator: 'logan',
    date: '2024-12-13',
    people: ['max'],
    type: 'graphic',
  },
  {
    kind: 'image',
    src: '/slander-gallery/Thornussy.png',
    alt: '',
    width: 998, height: 1460,
    date: '2025-08-06',
    people: ['logan', 'ethan'],
    type: 'text',
  },
  {
    kind: 'video',
    src: '/slander-gallery/FantasyWeekOneSlander.mov',
    alt: '',
    width: 400, height: 640,
    creator: 'logan',
    date: '2025-09-08',
    people: ['landon', 'robert', 'dillon', 'whieldon', 'cali', 'ethan', 'andy', 'matt'],
    type: 'video',
    poster: '/slander-gallery/FantasyWeekOneSlander.jpg',
  },
  {
    kind: 'image',
    src: '/slander-gallery/LoganWashed.jpg',
    alt: '',
    width: 492, height: 420,
    creator: 'andy',
    date: '2025-09-09',
    people: ['logan'],
    type: 'graphic',
  },
  {
    kind: 'image',
    src: '/slander-gallery/LandonFocusesOnGayButtStuff.jpg',
    alt: '',
    width: 1179, height: 1161,
    date: '2025-09-23',
    people: ['landon', 'ethan'],
    type: 'text',
  },
  {
    kind: 'video',
    src: '/slander-gallery/AndyFraudCalling.mov',
    alt: '',
    width: 360, height: 640,
    creator: 'robert',
    date: '2025-09-23',
    people: ['andy'],
    type: 'video',
    poster: '/slander-gallery/AndyFraudCalling.jpg',
  },
  {
    kind: 'video',
    src: '/slander-gallery/WhieldonCupcakes.mov',
    alt: '',
    width: 640, height: 352,
    creator: 'robert',
    date: '2025-09-23',
    people: ['whieldon'],
    type: 'video',
    poster: '/slander-gallery/WhieldonCupcakes.jpg',
  },
  {
    kind: 'video',
    src: '/slander-gallery/LetRobertCook.mov',
    alt: '',
    width: 360, height: 640,
    creator: 'robert',
    date: '2025-09-23',
    people: ['robert'],
    type: 'video',
    poster: '/slander-gallery/LetRobertCook.jpg',
  },
  {
    kind: 'video',
    src: '/slander-gallery/WhieldonThenNow.mov',
    alt: '',
    width: 480, height: 596,
    creator: 'robert',
    date: '2025-09-24',
    people: ['whieldon'],
    type: 'video',
    poster: '/slander-gallery/WhieldonThenNow.jpg',
  },
  {
    kind: 'video',
    src: '/slander-gallery/LoganFartedAgain.mov',
    alt: '',
    width: 360, height: 640,
    creator: 'robert',
    date: '2025-10-07',
    people: ['logan'],
    type: 'video',
    poster: '/slander-gallery/LoganFartedAgain.jpg',
  },
  {
    kind: 'video',
    src: '/slander-gallery/LoganLandonLossDance.mov',
    alt: '',
    width: 360, height: 640,
    creator: 'robert',
    date: '2025-10-07',
    people: ['logan', 'landon'],
    type: 'video',
    poster: '/slander-gallery/LoganLandonLossDance.jpg',
  },
  {
    kind: 'video',
    src: '/slander-gallery/AndyFraudIncomingCall.mov',
    alt: '',
    width: 360, height: 640,
    creator: 'robert',
    date: '2025-10-07',
    people: ['andy'],
    type: 'video',
    poster: '/slander-gallery/AndyFraudIncomingCall.jpg',
  },
  {
    kind: 'video',
    src: '/slander-gallery/RobertAndyJohnCena.mov',
    alt: '',
    width: 372, height: 640,
    creator: 'robert',
    date: '2025-10-07',
    people: ['robert', 'andy'],
    type: 'video',
    poster: '/slander-gallery/RobertAndyJohnCena.jpg',
  },
  {
    kind: 'youtube',
    videoId: '1y8Z5GJN3v8',
    alt: '',
    width: 1920, height: 1080,
    creator: 'robert',
    date: '2025-10-19',
    people: ['dillon', 'landon', 'matt', 'robert', 'andy', 'logan', 'james', 'whieldon', 'cali', 'ethan'],
    type: 'video',
  },
  {
    kind: 'video',
    src: '/slander-gallery/HowLoganConfusedTheLeague.mov',
    alt: '',
    width: 640, height: 356,
    creator: 'logan',
    date: '2025-10-21',
    people: ['logan'],
    type: 'video',
    poster: '/slander-gallery/HowLoganConfusedTheLeague.jpg',
  },
  {
    kind: 'video',
    src: '/slander-gallery/LoganHussein.mov',
    alt: '',
    width: 640, height: 268,
    creator: 'robert',
    date: '2025-10-22',
    people: ['logan'],
    type: 'video',
    poster: '/slander-gallery/LoganHussein.jpg',
  },
  {
    kind: 'image',
    src: '/slander-gallery/PowerRankingTierList.jpg',
    alt: '',
    width: 1007, height: 1222,
    creator: 'andy',
    date: '2025-10-25',
    people: ['logan', 'matt', 'robert', 'andy', 'max', 'whieldon', 'dillon', 'ethan', 'james', 'nick', 'cali', 'landon'],
    type: 'graphic',
  },
  {
    kind: 'image',
    src: '/slander-gallery/RobertOwnsMatt.jpg',
    alt: '',
    width: 930, height: 1203,
    creator: 'robert',
    date: '2025-11-19',
    people: ['robert', 'matt'],
    type: 'meme',
  },
  {
    kind: 'image',
    src: '/slander-gallery/EastDivisionDragon.jpg',
    alt: '',
    width: 561, height: 293,
    creator: 'logan',
    date: '2025-12-03',
    people: ['logan', 'robert', 'matt', 'robert'],
    type: 'meme',
  },
  {
    kind: 'image',
    src: '/slander-gallery/RobertLoganOwnMatt.jpg',
    alt: '',
    width: 1536, height: 1026,
    creator: 'logan',
    date: '2025-12-03',
    people: ['logan', 'robert', 'matt'],
    type: 'meme',
  },
  {
    kind: 'video',
    src: '/slander-gallery/EastDancingInThePlayoffs.mov',
    alt: '',
    width: 640, height: 348,
    creator: 'logan',
    date: '2025-12-10',
    people: ['james', 'logan', 'robert', 'matt'],
    type: 'video',
    poster: '/slander-gallery/EastDancingInThePlayoffs.jpg',
  },
  {
    kind: 'youtube',
    videoId: 'PGS5A_JeEjo',
    alt: '',
    width: 1920, height: 1080,
    creator: 'andy',
    date: '2025-12-11',
    people: ['landon'],
    type: 'video',
  },
  {
    kind: 'image',
    src: '/slander-gallery/MattPackwatchLandon.png',
    alt: '',
    width: 1021, height: 1091,
    date: '2025-12-15',
    people: ['matt', 'landon'],
    type: 'text',
  },
  {
    kind: 'image',
    src: '/slander-gallery/JamesBeatsWhieldon.jpg',
    alt: '',
    width: 1179, height: 1634,
    date: '2026-01-04',
    people: ['james', 'whieldon'],
    type: 'text',
  },
  {
    kind: 'image',
    src: '/slander-gallery/RobertAutismAwareness.jpg',
    alt: '',
    width: 1125, height: 1377,
    creator: 'brady',
    date: '2026-08-29',
    people: ['robert'],
    type: 'meme',
  },
  {
    kind: 'image',
    src: '/slander-gallery/BradyLGBTQ.jpg',
    alt: '',
    width: 1122, height: 1402,
    creator: 'robert',
    date: '2026-08-29',
    people: ['brady'],
    type: 'meme',
  },
  {
    kind: 'image',
    src: '/slander-gallery/BradyTransition.jpg',
    alt: '',
    width: 1024, height: 1536,
    creator: 'robert',
    date: '2026-08-29',
    people: ['brady'],
    type: 'meme',
  },
  {
    kind: 'image',
    src: '/slander-gallery/MaxPortrait.png',
    alt: '',
    width: 456, height: 569,
    creator: 'logan',
    date: '2029-09-15',
    people: ['max','dillon','ethan','andy','brady','andrew','landon','whieldon','logan','matt','james','robert'],
    type: 'meme',
  },
  {
    kind: 'youtube',
    videoId: 'XvRy6cckuCk',
    alt: '',
    width: 1920, height: 1080,
    creator: 'robert',
    date: '2026-09-17',
    people: ['matt'],
    type: 'video',
  },
  {
    kind: 'image',
    src: '/slander-gallery/AndrewDragon.jpg',
    alt: '',
    width: 680, height: 544,
    creator: 'andrew',
    date: '2026-09-20',
    people: ['andrew'],
    type: 'meme',
  },
]